# Simple makefile for PeTaL-Labeller/auto-labeler/MATCH
# MATCH on PeTaL Data
# Created by Eric Kong (erickongl@gmail.com, eric.l.kong@nasa.gov).
# Last modified by Eric Kong on 21 July 2021.

all:
	python3 setup.py --verbose

clean:
	rm PeTaL.tar.gz || true
	rm -r src/MATCH/PeTaL || true
	rm -r src/wandb || true
