model: MATCH
dataset: PeTaL

split:
  prefix: MATCH/PeTaL
  dataset: cleaned_lens_output.json
  train: 0.8
  dev: 0.1
  skip: 0

transform:
  prefix: MATCH
  dataset: PeTaL
  use_mag: True
  use_mesh: True
  use_venue: True
  use_author: True
  use_reference: True
  use_text: True

preprocess:
  prefix: MATCH
  vocab_size: 500000
  max_len: 500

train:
  prefix: MATCH
  hypernymy_regularization: True
  leaf_labels_only: False
  notes: ''

wandb:
  project: MATCH
  group: integration_20210714a
