name: MATCH

model:
  hidden_size: 100
  n_layers: 3
  n_probes: 8
  n_aheads: 2
  intermediate_size: 800
  dropout: 0.1
  src_max_len: 500

train:
  batch_size: 8 # 256
  step: 10
  nb_epoch: 1000
  swa_warmup: 4
  early: 25
  learning_rate: 0.002
  weight_decay: 0
  beta1: 0.9
  beta2: 0.999

valid:
  batch_size: 8

predict:
  batch_size: 8

path: PeTaL/models  
